openapi: 3.0.1
info:
  title: 77Sol Project API
  description: API para o projeto 77Sol
  version: "1.0.0"
  
tags: 
  - name: Login
  - name: Customers
  - name: Projects
  - name: Equipments
  - name: Installation Types

servers:
  - url: "http://localhost:8085"

paths:
  /api/login:
    post:
      summary: Login
      tags:
        - Login
      description: Login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login efetuado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenciais inválidas.

  /api/customers:
    get:
      summary: Get All Customers
      tags:
        - Customers
      description: Retorna uma lista de clientes com base nos parâmetros de consulta.
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: string
        - name: document
          in: query
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de clientes retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    document:
                      type: string
    post:
      summary: New Customer
      tags:
        - Customers
      description: Cria um novo cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                document:
                  type: string
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Cliente criado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "400":
          description: Documento inválido
        "422":
          description: Parâmetros inválidos

  /api/customers/{id}:
    get:
      summary: Get Customer By ID
      tags:
        - Customers
      description: Retorna um cliente específico pelo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Cliente encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "422":
          description: Parâmetros inválidos
    put:
      summary: Update Customer
      tags:
        - Customers
      description: Atualiza informações de um cliente específico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                document:
                  type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Cliente atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "400":
          description: Documento inválido
        "404":
          description: Cliente não encontrado.
        "422":
          description: Parâmetros inválidos

    delete:
      summary: Delete Customer
      tags:
        - Customers
      description: Exclui um cliente específico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Cliente excluído com sucesso.
        "404":
          description: Cliente não encontrado.

  /api/projects:
    get:
      tags:
        - Projects
      summary: Get all Projects
      parameters:
        - in: query
          name: id
          schema:
            type: integer
        - in: query
          name: customer_id
          schema:
            type: integer
        - in: query
          name: installation_type_id
          schema:
            type: integer
        - in: query
          name: location
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de projetos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    location:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    customer:
                      type: object
                      nullable: true
                    installation_type:
                      type: object
                      properties:
                        id:
                          type: integer
                        description:
                          type: string
                    equipments:
                      type: array
                      items:
                        type: object
                        properties:
                          quantity:
                            type: integer
                          equipment:
                            type: object
                            properties:
                              id:
                                type: integer
                              description:
                                type: string
        "422":
          description: Parâmetros inválidos

    post:
      tags:
        - Projects
      summary: Create new Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                installation_type_id:
                  type: integer
                location:
                  type: string
              example:
                customer_id: 1
                installation_type_id: 1
                location: "SP"
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Projeto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  id:
                    type: integer
        "404":
          description: Tipo de instalação não encontrado
        "422":
          description: Parâmetros inválidos

  /api/projects/{projectId}:
    get:
      tags:
        - Projects
      summary: Get Project by ID
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Projeto retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  location:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  customer:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  installation_type:
                    type: object
                    properties:
                      id:
                        type: integer
                      description:
                        type: string
                  equipments:
                    type: array
                    items:
                      type: object
                      properties:
                        quantity:
                          type: integer
                        equipment:
                          type: object
                          properties:
                            id:
                              type: integer
                            description:
                              type: string
        "404":
          description: Projeto não encontrado

    put:
      tags:
        - Projects
      summary: Update Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                installation_type_id:
                  type: integer
                location:
                  type: string
              example:
                customer_id: 1
                installation_type_id: 2
                location: "SP"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Projeto atualizado com sucesso
          content:
            application/json:
              schema:
                type: boolean
                example: true
        "404":
          description: Projeto ou Tipo de Instalação não encontrado
        "422":
          description: Parâmetros inválidos

    delete:
      tags:
        - Projects
      summary: Delete Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Projeto excluído com sucesso
          content:
            application/json:
              schema:
                type: boolean
                example: true
        "404":
          description: Projeto não encontrado

  /api/projects/{projectId}/equipment:
    post:
      tags:
        - Projects
      summary: Add new Equipment to Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                equipment_id:
                  type: integer
                quantity:
                  type: integer
              example:
                equipment_id: 5
                quantity: 3
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Equipamento adicionado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  equipment_id:
                    type: integer
                  quantity:
                    type: integer
        "404":
          description: Projeto ou Equipamento não encontrado
        "422":
          description: Parâmetros inválidos

  /api/projects/{projectId}/equipment/{equipmentId}:
    put:
      tags:
        - Projects
      summary: Update Equipment in Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
        - in: path
          name: equipmentId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Equipamento atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                example: {}
        "404":
          description: Projeto ou Equipamento não encontrado
        "422":
          description: Parâmetros inválidos

    delete:
      tags:
        - Projects
      summary: Remove Equipment from Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
        - in: path
          name: equipmentId
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Equipamento removido com sucesso
          content:
            application/json:
              schema:
                type: boolean
                example: true
        "404":
          description: Projeto ou Equipamento não encontrado

  /api/installationTypes:
    get:
      summary: Get All Installation Types
      tags:
        - Installation Types
      description: Retorna uma lista de tipos de instalação.
      parameters:
        - name: id
          in: query
          schema:
            type: integer
        - name: description
          in: query
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de tipos de instalação retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    description:
                      type: string
        "422":
          description: Parâmetros inválidos

  /api/installationTypes/{id}:
    get:
      summary: Get Installation Type By ID
      tags:
        - Installation Types
      description: Retorna um tipo de instalação específico pelo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Tipo de instalação encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  description:
                    type: string
        "404":
          description: Tipo de instalação não encontrado.

  /api/equipments:
    get:
      summary: Get All Equipments
      tags:
        - Equipments
      description: Retorna uma lista de equipamentos.
      parameters:
        - name: id
          in: query
          schema:
            type: integer
        - name: description
          in: query
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de equipamentos retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    description:
                      type: string
        "422":
          description: Parâmetros inválidos

  /api/equipments/{id}:
    get:
      summary: Get Equipment By ID
      tags:
        - Equipments
      description: Retorna um equipamento específico pelo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Equipamento encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  description:
                    type: string
        "404":
          description: Equipamento não encontrado.

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: header
      name: Authorization